### ISSUE TITLE
Quantile-Rainbow: is gamma discounting for n-step rewards included?

### ISSUE THREAD

**Issue by dannysdeng** [qfettes/DeepRL-Tutorials#1]
This is a great repo for us pytorch users trying to learning RL and I really appreciate the cleaness of the code.

I spotted that in the Quantile-Rainbow notebook, there does not seem to be _n-step_ gamma discounting as in the Rainbow notebook. 
Is there a particular reason to to do 
`quantiles_next = batch_reward + (self.gamma*quantiles_next)` 
in the _Agent_ cell in _10.Quantile-Rainbow.ipynb_ ?

Cuz I was expecting something like
`quantiles_next = batch_reward + ((self.gamma**self.nsteps)*quantiles_next) `

Thanks in advance!

**Comment by qfettes** [comment]
@dannysdeng good catch! Indeed, the Quantile Rainbow code used n-step learning, so it should read as you described. I pushed changes to correct this error.
