### ISSUE TITLE
Model has no finish_nstep

### ISSUE THREAD

**Issue by data-compute-geek** [qfettes/DeepRL-Tutorials#2]
Hi Quintin,

Class Model has no attribute finish_nstep or reset_hx. Would you please add them?

Thanks.
Sean

**Comment by qfettes** [comment]
Hi,

Could you elaborate more? Which IPython notebook or Agent/ file are you working from?

**Comment by data-compute-geek** [comment]
https://github.com/qfettes/DeepRL-Tutorials/blob/master/01.DQN.ipynb

**Comment by qfettes** [comment]
Thanks, this bug was introduced when I standardized the main training loops in the notebooks. It has been corrected.
