### ISSUE TITLE
01.DQN.ipynb all_rewards, losses not defined?

### ISSUE THREAD

**Issue by 1576012404** [qfettes/DeepRL-Tutorials#5]
01.DQN.ipynb all_rewards, losses not defined?

**Comment by qfettes** [comment]
Good catch! I broke that section of plotting code when I changed it. Thanks for the help, it's fixed now.

**Comment by 1576012404** [comment]
thank you! i will carefully read to learn you codes! you are so excellent!

**Comment by 1576012404** [comment]
Could you write TRPO algorithm in the following time? I think it very import ,thanks a lot!

**Comment by qfettes** [comment]
Thank you. Indeed, TRPO is an important algorithm, as it helped pioneer trust region optimization in Deep Reinforcement Learning. It's on the list of algorithms I'd like to implement
