### ISSUE TITLE
Reward does not increase in Colab

### ISSUE THREAD

**Issue by diogohmcruz** [qfettes/DeepRL-Tutorials#8]
I've made a Google Colab to train the [01.DQN.ipynb](https://github.com/qfettes/DeepRL-Tutorials/blob/master/01.DQN.ipynb) but the reward is not increasing.

![colab train](https://user-images.githubusercontent.com/9451036/53357976-fe547880-3926-11e9-872c-121d86a2a935.png)

**Comment by diogohmcruz** [comment]
I've trained some more and it is increasing more.
My bad. Should have trained more for the first time.
Your graph shows great results faster than mine.

![updated colab rewards](https://user-images.githubusercontent.com/9451036/53359688-8fc5e980-392b-11e9-926a-7587885f2bb2.png)

**Comment by qfettes** [comment]
Indeed. A seed is never set in the code so you should expect some variance between runs. I'm glad you were able to figure it out.
